// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpChqfUSE8kwbjRQ7kqn1kReyiWYAoni0',
    appId: '1:216407057129:web:a7dead6c66058139858678',
    messagingSenderId: '216407057129',
    projectId: 'loginapp-c96e0',
    authDomain: 'loginapp-c96e0.firebaseapp.com',
    storageBucket: 'loginapp-c96e0.appspot.com',
    measurementId: 'G-X8KZPH1EDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqd3xvKfsIZWgE3tfiHnql0AUpsHABub8',
    appId: '1:216407057129:android:0566e3752e6732bb858678',
    messagingSenderId: '216407057129',
    projectId: 'loginapp-c96e0',
    storageBucket: 'loginapp-c96e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlYfcrgcAWzoTP9Dcb9QzFz_ErluysqQ',
    appId: '1:216407057129:ios:cb0661598e827ed9858678',
    messagingSenderId: '216407057129',
    projectId: 'loginapp-c96e0',
    storageBucket: 'loginapp-c96e0.appspot.com',
    iosBundleId: 'com.example.loginAppBlocAndFirebase',
  );
}
